databases:
  - name: indiebank_db
    databaseName: indiebank
    user: indiebank
    plan: free

services:
  - type: web
    name: indiebank
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn banking_project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: indiebank_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
