from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib import messages
from django.db import transaction
from django.contrib.auth.models import User
from decimal import Decimal, InvalidOperation
from .models import Account, Transaction, CustomerProfile, Notification, Complaint, CreditCardApplication, LoanApplication

def is_admin(user):
    return user.is_authenticated and user.is_staff

@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_dashboard(request):
    pending_transactions = Transaction.objects.filter(status='PENDING')
    pending_accounts = CustomerProfile.objects.filter(is_approved=False)
    all_transactions = Transaction.objects.all()[:20]
    total_balance = sum(Account.objects.values_list('balance', flat=True))
    pending_complaints = Complaint.objects.filter(status='PENDING').count()
    
    context = {
        'pending_transactions': pending_transactions,
        'pending_accounts': pending_accounts,
        'all_transactions': all_transactions,
        'total_balance': total_balance,
        'pending_complaints': pending_complaints,
    }
    return render(request, 'admin_dashboard.html', context)

@login_required
@user_passes_test(is_admin, login_url='/login/')
def approve_transaction(request, transaction_id):
    txn = get_object_or_404(Transaction, id=transaction_id)
    if txn.status == 'PENDING':
        with transaction.atomic():
            txn.status = 'APPROVED'
            txn.save()

            # Logic for different transaction types
            if txn.transaction_type == 'CREDIT':
                # This was a pending deposit
                txn.account.balance += txn.amount
                txn.account.save()
            
            elif txn.transaction_type == 'DEBIT' and txn.receiver_account:
                # This was a pending transfer
                # Sender balance was already deducted in the initial view
                txn.receiver_account.balance += txn.amount
                txn.receiver_account.save()
                
                # Create a credit transaction for the receiver
                Transaction.objects.create(
                    account=txn.receiver_account,
                    description=f"Transfer from A/C {txn.account.account_number}",
                    amount=txn.amount,
                    transaction_type='CREDIT',
                    status='APPROVED'
                )
            
        messages.success(request, f"Transaction {txn.id} approved.")
    return redirect('admin_dashboard')

@login_required
@user_passes_test(is_admin, login_url='/login/')
def reject_transaction(request, transaction_id):
    txn = get_object_or_404(Transaction, id=transaction_id)
    if txn.status == 'PENDING':
        with transaction.atomic():
            # If it was a debit, we need to refund the account because it was already deducted in the initial view
            if txn.transaction_type == 'DEBIT':
                txn.account.balance += txn.amount
                txn.account.save()
            txn.status = 'REJECTED'
            txn.save()
            messages.warning(request, f"Transaction {txn.id} rejected and funds reverted.")
    return redirect('admin_dashboard')

@login_required
@user_passes_test(is_admin, login_url='/login/')
def approve_account(request, profile_id):
    profile = get_object_or_404(CustomerProfile, id=profile_id)
    profile.is_approved = True
    profile.save()

    # Autogenerated message for the user
    account = Account.objects.filter(user=profile.user).first()
    acc_num = account.account_number if account else "N/A"
    pan_num = profile.pan_number if profile.pan_number else "N/A"
    Notification.objects.create(
        user=profile.user,
        title="Account Approved - Welcome to Indie Bank",
        message=(
            f"Congratulations {profile.user.username}! Your account has been approved.\n\n"
            f"Customer ID: {profile.user.id}\n"
            f"Account Number: {acc_num}\n"
            f"PAN Number: {pan_num}\n"
            f"Password: [As set during registration]\n\n"
            "You can now log in and access all banking services."
        ),
        notification_type='SYSTEM'
    )

    # Send Email
    if profile.user.email:
        email_subject = "Welcome to Indie Bank - Account Approved"
        email_body = (
            f"Dear {profile.user.first_name or profile.user.username},\n\n"
            f"Congratulations! Your Indie Bank account has been approved and is now active.\n\n"
            f"Customer ID: {profile.user.id}\n"
            f"Account Number: {acc_num}\n"
            f"PAN Number: {pan_num}\n"
            f"Password: [The password you chose during registration]\n\n"
            "You can now log in to the portal and start using our digital banking services.\n\n"
            "Thank you for choosing Indie Bank.\n"
            "Best Regards,\n"
            "The Indie Bank Team"
        )
        send_mail(
            email_subject,
            email_body,
            'support@indiebank.com',
            [profile.user.email],
            fail_silently=True,
        )

    messages.success(request, f"Account for {profile.user.username} approved and notification sent.")
    return redirect('admin_dashboard')


# ─── Credit Card Application Management ─────────────────────────────────────

@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_credit_card_list(request):
    """List all credit card applications for the admin."""
    applications = CreditCardApplication.objects.all().select_related('user').order_by('-applied_at')
    context = {
        'applications': applications,
        'pending_count': applications.filter(status='PENDING').count(),
    }
    return render(request, 'admin_credit_cards.html', context)


@login_required
@user_passes_test(is_admin, login_url='/login/')
def approve_credit_card(request, app_id):
    """Approve a credit card application, create the account, and notify the user."""
    if request.method != 'POST':
        return redirect('admin_credit_card_list')

    application = get_object_or_404(CreditCardApplication, id=app_id, status='PENDING')
    assigned_type = request.POST.get('assigned_card_type', 'SILVER').upper()
    credit_limit_str = request.POST.get('credit_limit', '0').replace(',', '')
    admin_remarks = request.POST.get('admin_remarks', '')

    try:
        credit_limit = float(credit_limit_str)
    except (ValueError, TypeError):
        messages.error(request, 'Invalid credit limit value.')
        return redirect('admin_credit_card_list')

    with transaction.atomic():
        # Update application status
        application.status = 'APPROVED'
        application.assigned_card_type = assigned_type
        application.credit_limit = credit_limit
        application.admin_remarks = admin_remarks
        application.save()

        # Generate a unique credit card account number  
        import random
        while True:
            card_acc_num = f"CC{''.join(random.choices('0123456789', k=10))}"
            if not Account.objects.filter(account_number=card_acc_num).exists():
                break

        # Create the credit card account for the user with credit_limit as balance
        Account.objects.create(
            user=application.user,
            account_number=card_acc_num,
            account_type='CREDIT',
            balance=credit_limit,
            card_type=assigned_type,
            credit_limit=credit_limit,
        )

        card_labels = {'PLATINUM': 'Platinum', 'GOLD': 'Gold', 'SILVER': 'Silver'}
        card_label = card_labels.get(assigned_type, assigned_type.capitalize())

        # Notify the user
        Notification.objects.create(
            user=application.user,
            title=f"🎉 Your {card_label} Credit Card is Approved!",
            message=(
                f"Congratulations {application.user.first_name or application.user.username}! "
                f"Your application for a {card_label} Credit Card has been approved.\n\n"
                f"Card Number: {card_acc_num}\n"
                f"Credit Limit: ₹{credit_limit:,.0f}\n"
                f"Card Type: {card_label}\n\n"
                + (f"Admin Remarks: {admin_remarks}" if admin_remarks else "You can now use your credit card for purchases.")
            ),
            notification_type='CREDIT_CARD'
        )

    messages.success(request, f"{card_label} Card approved for {application.user.username}. Account {card_acc_num} created with ₹{credit_limit:,.0f} limit.")
    return redirect('admin_credit_card_list')


@login_required
@user_passes_test(is_admin, login_url='/login/')
def reject_credit_card(request, app_id):
    """Reject a credit card application and notify the user."""
    if request.method != 'POST':
        return redirect('admin_credit_card_list')

    application = get_object_or_404(CreditCardApplication, id=app_id, status='PENDING')
    admin_remarks = request.POST.get('admin_remarks', 'Your application did not meet our current eligibility criteria.')

    application.status = 'REJECTED'
    application.admin_remarks = admin_remarks
    application.save()

    Notification.objects.create(
        user=application.user,
        title=f"Credit Card Application Update",
        message=(
            f"We regret to inform you that your application for a "
            f"{application.get_requested_card_type_display()} Credit Card has been rejected.\n\n"
            f"Reason: {admin_remarks}\n\n"
            "Please contact our support team for more information."
        ),
        notification_type='CREDIT_CARD'
    )

    messages.warning(request, f"Application for {application.user.username} has been rejected.")
    return redirect('admin_credit_card_list')

# ─── Loan Application Management ─────────────────────────────────────────────

@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_loan_list(request):
    """List all loan applications for the admin."""
    applications = LoanApplication.objects.all().select_related('user').order_by('-applied_at')
    context = {
        'applications': applications,
        'pending_count': applications.filter(status='PENDING').count(),
    }
    return render(request, 'admin_loans.html', context)


@login_required
@user_passes_test(is_admin, login_url='/login/')
def approve_loan(request, app_id):
    """Approve a loan application and notify the user."""
    if request.method != 'POST':
        return redirect('admin_loan_list')

    application = get_object_or_404(LoanApplication, id=app_id, status='PENDING')
    admin_remarks = request.POST.get('admin_remarks', 'Your loan application meets our criteria.')

    with transaction.atomic():
        # Update application status
        application.status = 'APPROVED'
        application.admin_remarks = admin_remarks
        application.save()

        # Logic: Credit the loan amount to the user's primary savings account
        primary_account = Account.objects.filter(user=application.user, account_type='SAVINGS').first()
        if primary_account:
            primary_account.balance += application.amount
            primary_account.save()

            # Create a transaction record
            Transaction.objects.create(
                account=primary_account,
                description=f"Loan Disbursement: {application.get_loan_type_display()}",
                amount=application.amount,
                transaction_type='CREDIT',
                status='APPROVED'
            )

        # Notify the user
        Notification.objects.create(
            user=application.user,
            title=f"✅ Your {application.get_loan_type_display()} is Approved!",
            message=(
                f"Congratulations {application.user.first_name or application.user.username}! "
                f"Your request for a {application.get_loan_type_display()} of ₹{application.amount:,.2f} has been approved.\n\n"
                f"The amount has been credited to your primary account.\n"
                f"Tenure: {application.tenure_years} Years\n\n"
                + (f"Admin Remarks: {admin_remarks}" if admin_remarks else "")
            ),
            notification_type='SYSTEM'
        )

    messages.success(request, f"{application.get_loan_type_display()} approved for {application.user.username}. ₹{application.amount:,.2f} credited.")
    return redirect('admin_loan_list')


@login_required
@user_passes_test(is_admin, login_url='/login/')
def reject_loan(request, app_id):
    """Reject a loan application and notify the user."""
    if request.method != 'POST':
        return redirect('admin_loan_list')

    application = get_object_or_404(LoanApplication, id=app_id, status='PENDING')
    admin_remarks = request.POST.get('admin_remarks', 'Your application does not meet the bank\'s internal risk policies.')

    application.status = 'REJECTED'
    application.admin_remarks = admin_remarks
    application.save()

    Notification.objects.create(
        user=application.user,
        title=f"Loan Application Update",
        message=(
            f"We regret to inform you that your application for a "
            f"{application.get_loan_type_display()} has been rejected.\n\n"
            f"Reason: {admin_remarks}\n\n"
            "Please contact your branch for more details."
        ),
        notification_type='SYSTEM'
    )

    messages.warning(request, f"Loan application for {application.user.username} rejected.")
    return redirect('admin_loan_list')

# ─── User Management ─────────────────────────────────────────────────────────

@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_users_list(request):
    """View all users and their KYC status."""
    profiles = CustomerProfile.objects.all().select_related('user').order_by('-user__date_joined')
    context = {'profiles': profiles}
    return render(request, 'admin_users.html', context)

@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_add_user(request):
    """Manually onboard a new customer."""
    if request.method == 'POST':
        u = request.POST.get('username')
        e = request.POST.get('email')
        fn = request.POST.get('first_name', '')
        ln = request.POST.get('last_name', '')
        p = request.POST.get('password')
        pan = request.POST.get('pan_number', '')

        if User.objects.filter(username=u).exists():
            messages.error(request, f"Username {u} already exists.")
            return redirect('admin_users_list')

        try:
            with transaction.atomic():
                user = User.objects.create_user(username=u, email=e, password=p, first_name=fn, last_name=ln)
                # Check if profile already created via signals
                profile, created = CustomerProfile.objects.get_or_create(user=user)
                profile.pan_number = pan
                profile.is_approved = True
                profile.save()
                
                # Create a basic account for them
                acc_num = f"1000{user.id:08d}"
                Account.objects.get_or_create(user=user, defaults={'account_number': acc_num})
                
            messages.success(request, f"User {u} onboarded successfully.")
        except Exception as e:
            messages.error(request, f"Error: {str(e)}")
            
    return redirect('admin_users_list')

@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_edit_user(request, user_id):
    """Edit user details and KYC status."""
    target_user = get_object_or_404(User, id=user_id)
    profile = get_object_or_404(CustomerProfile, user=target_user)
    
    if request.method == 'POST':
        target_user.first_name = request.POST.get('first_name')
        target_user.last_name = request.POST.get('last_name')
        target_user.email = request.POST.get('email')
        target_user.save()
        
        profile.pan_number = request.POST.get('pan_number')
        profile.is_approved = 'is_approved' in request.POST
        profile.save()
        
        messages.success(request, f"User {target_user.username} updated.")
        return redirect('admin_users_list')
        
    # Fetch all bank accounts for this user
    accounts = Account.objects.filter(user=target_user)
    
    context = {
        'target_user': target_user,
        'profile': profile,
        'accounts': accounts
    }
    return render(request, 'admin_edit_user.html', context)


@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_reset_user_password(request, user_id):
    """Manually reset a user's password (admin)."""
    if request.method == 'POST':
        target_user = get_object_or_404(User, id=user_id)
        new_password = request.POST.get('new_password')
        
        if new_password:
            target_user.set_password(new_password)
            target_user.save()
            messages.success(request, f"Password for {target_user.username} has been successfully reset.")
        else:
            messages.error(request, "Password cannot be empty.")
            
    return redirect('admin_edit_user', user_id=user_id)

@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_user_transactions(request, user_id):
    """View transaction history for a specific customer."""
    target_user = get_object_or_404(User, id=user_id)
    accounts = Account.objects.filter(user=target_user)
    transactions = Transaction.objects.filter(account__user=target_user).select_related('account', 'receiver_account').order_by('-date')
    
    context = {
        'target_user': target_user,
        'accounts': accounts,
        'transactions': transactions,
    }
    return render(request, 'admin_user_transactions.html', context)

@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_remove_user(request, user_id):
    """Permanently delete a user."""
    target_user = get_object_or_404(User, id=user_id)
    if target_user.is_superuser:
        messages.error(request, "Cannot delete a superuser.")
    else:
        username = target_user.username
        target_user.delete()
        messages.warning(request, f"User {username} has been terminated.")
    return redirect('admin_users_list')

# ─── Account Management ──────────────────────────────────────────────────────

@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_accounts_list(request):
    """List all accounts for the admin."""
    accounts = Account.objects.select_related('user').all().order_by('-created_at')
    
    total_liquidity = sum(a.balance for a in accounts if a.account_type != 'LOAN')
    active_accounts = accounts.count()
    
    context = {
        'accounts': accounts,
        'total_liquidity': total_liquidity,
        'active_accounts': active_accounts,
    }
    return render(request, 'admin_accounts.html', context)


@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_add_account(request):
    """Manually create a bank account for a user."""
    if request.method == 'POST':
        username = request.POST.get('username', '').strip()
        account_type = request.POST.get('account_type', 'SAVINGS')
        initial_balance_str = request.POST.get('initial_balance', '0')

        target_user = User.objects.filter(username=username).first()
        if not target_user:
            messages.error(request, f'No user found with username "{username}".')
            return redirect('admin_accounts_list')

        try:
            initial_balance = Decimal(initial_balance_str)
            if initial_balance < Decimal('0'):
                raise InvalidOperation
        except InvalidOperation:
            messages.error(request, 'Invalid initial balance.')
            return redirect('admin_accounts_list')

        try:
            with transaction.atomic():
                import random
                while True:
                    acc_num = ''.join(random.choices('0123456789', k=10))
                    if not Account.objects.filter(account_number=acc_num).exists():
                        break

                account = Account.objects.create(
                    user=target_user,
                    account_number=acc_num,
                    account_type=account_type,
                    balance=initial_balance,
                )

                if initial_balance > Decimal('0'):
                    Transaction.objects.create(
                        account=account,
                        amount=initial_balance,
                        transaction_type='CREDIT',
                        status='APPROVED',
                        description='[ADMIN_OVERRIDE] Initial account funding'
                    )

            messages.success(request, f'Account {acc_num} created for {username} with balance ₹{initial_balance:,.2f}.')
        except Exception as ex:
            messages.error(request, f'Error creating account: {str(ex)}')

    return redirect('admin_accounts_list')


# ─── Transaction Management ──────────────────────────────────────────────────

@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_transactions_list(request):
    """View the global ledger."""
    transactions = Transaction.objects.select_related('account__user', 'receiver_account__user').all().order_by('-date')
    context = {
        'transactions': transactions,
    }
    return render(request, 'admin_transactions.html', context)


@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_add_transaction(request):
    """Admin endpoint to forcefully manually create a transaction."""
    if request.method == 'POST':
        account_number = request.POST.get('account_number')
        amount_str = request.POST.get('amount')
        transaction_type = request.POST.get('transaction_type')
        description = request.POST.get('description', 'Admin Manual Override')

        try:
            amount = Decimal(amount_str)
            if amount <= Decimal('0'):
                raise InvalidOperation
        except (InvalidOperation, TypeError):
            messages.error(request, 'Invalid amount provided.')
            return redirect('admin_transactions_list')

        account = Account.objects.filter(account_number=account_number).first()
        if not account:
            messages.error(request, f'Account number {account_number} not found.')
            return redirect('admin_transactions_list')

        try:
            with transaction.atomic():
                if transaction_type == 'CREDIT':
                    account.balance = account.balance + amount
                elif transaction_type == 'DEBIT':
                    if account.balance < amount:
                        messages.warning(request, f'Warning: Balance will go negative after this debit.')
                    account.balance = account.balance - amount
                else:
                    messages.error(request, 'Invalid transaction type.')
                    return redirect('admin_transactions_list')
                
                account.save()
                
                # Log transaction
                Transaction.objects.create(
                    account=account,
                    amount=amount,
                    transaction_type=transaction_type,
                    status='APPROVED',
                    description=f"[ADMIN_OVERRIDE] {description}"
                )
                
            messages.success(request, f'Successfully applied {transaction_type} of ₹{amount:,.2f} to {account_number}.')
        except Exception as e:
            messages.error(request, f'Error creating transaction: {str(e)}')

    # Check for a next URL in query or referral header
    next_url = request.GET.get('next') or request.META.get('HTTP_REFERER')
    return redirect(next_url if next_url else 'admin_transactions_list')


@login_required
@user_passes_test(is_admin, login_url='/login/')
def admin_complaints(request):
    """View all customer complaints."""
    complaints = Complaint.objects.all().order_by('-created_at')
    return render(request, 'admin_complaints.html', {'complaints': complaints})


@login_required
@user_passes_test(is_admin, login_url='/login/')
def update_complaint_status(request, pk):
    """Update complaint status and notify user (admin)."""
    if request.method == 'POST':
        complaint = get_object_or_404(Complaint, pk=pk)
        new_status = request.POST.get('status')
        if new_status in ['PENDING', 'IN_PROGRESS', 'RESOLVED']:
            complaint.status = new_status
            complaint.save()
            
            if complaint.user:
                Notification.objects.create(
                    user=complaint.user,
                    title=f"Complaint Status Update: {complaint.complaint_id}",
                    message=f"The status of your complaint ({complaint.complaint_id}) is now: {complaint.get_status_display()}.",
                    notification_type='COMPLAINT'
                )
            messages.success(request, f"Complaint {complaint.complaint_id} updated.")
    return redirect('admin_complaints')
