# Generated by Django 6.0.3 on 2026-03-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='query_type',
            field=models.CharField(choices=[('ACCOUNT', 'Account Related'), ('LOAN', 'Loan Inquiry'), ('CARD', 'Credit Card Support'), ('TECH', 'Technical Issue'), ('OTHER', 'Other'), ('GENERAL', 'General Support')], default='GENERAL', max_length=20),
        ),
    ]
