# Generated by Django 6.0.3 on 2026-03-29 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_notification_notification_type_beneficiary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_USER', 'New User Registration'), ('LOGIN_ATTEMPT', 'Unapproved Login Attempt'), ('SYSTEM', 'System Alert'), ('TRANSACTION', 'Transaction Alert'), ('COMPLAINT', 'Complaint Update')], default='SYSTEM', max_length=20),
        ),
    ]
