# Generated by Django 6.0.3 on 2026-03-30 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bill_paymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtransfer',
            name='last_run',
        ),
        migrations.RemoveField(
            model_name='scheduledtransfer',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='scheduledtransfer',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtransfer',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
