# Generated by Django 6.0.3 on 2026-03-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_account_card_type_account_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_USER', 'New User Registration'), ('LOGIN_ATTEMPT', 'Unapproved Login Attempt'), ('SYSTEM', 'System Alert'), ('TRANSACTION', 'Transaction Alert'), ('COMPLAINT', 'Complaint Update'), ('CREDIT_CARD', 'Credit Card Application')], default='SYSTEM', max_length=20),
        ),
    ]
